# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b1ebf2177ff93131471329121657373436ff4a3b1c278a2467e4a512ed60d9b543fdfc4a38d3c659326a2ec9f2e382db94b0db1b2bdbe9e00ea9ab5e8dc1d7e

test:
  secret_key_base: 43bf1c5d63c67879f8953a61e9b6fa5f93d2bc672f2cb66cbfacec3efca4bd22b1f67435c98d828f6438cb11d0c4b492bb9cb36b8638ca89b32b755d4c31adbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
